import { useState } from 'react';
import { Alert, Button, Card, Form, Input, InputNumber, Modal, Popconfirm, Select, Space, Switch, Table, Typography, message } from 'antd';
import { api } from '../api';
import { useAuth } from '../auth/AuthContext';
import { DataState, useP2Data } from '../components/P2Data';

interface Preference { trafficEnabled: boolean; expirationEnabled: boolean; revision: number }
function Rules() {
  const query = useP2Data<Array<Record<string, any>>>('/api/alert-rules');
  const [editing, setEditing] = useState<Record<string, any> | null>(null);
  const [form] = Form.useForm();
  const save = async () => { try { const values = await form.validateFields(); await api.request(editing?.id ? `/api/alert-rules/${editing.id}` : '/api/alert-rules', editing?.id ? 'PUT' : 'POST', { ...values, thresholds: values.thresholds.split(',').map((value: string) => Number(value.trim())), scopeId: values.scopeType === 'all' ? null : values.scopeId, channel: 'email', expectedRevision: editing?.revision }); setEditing(null); void query.load(); } catch (error) { message.error(error instanceof Error ? error.message : '请检查规则字段'); } };
  return <Card title="系统告警规则（owner）" extra={<Button onClick={() => { setEditing({}); form.setFieldsValue({ name: '', kind: 'traffic_limit', enabled: true, scopeType: 'all', thresholds: '80,90,100' }); }}>新建规则</Button>}><DataState {...query} retry={query.load} /><Table rowKey="id" dataSource={query.data || []} columns={[{ title: '名称', dataIndex: 'name' }, { title: '类型', dataIndex: 'kind' }, { title: '范围', dataIndex: 'scopeType' }, { title: '阈值', dataIndex: 'thresholds', render: (value: number[]) => value.join(', ') }, { title: '操作', render: (_, row) => <Space><Button onClick={() => { setEditing(row); form.setFieldsValue({ ...row, thresholds: row.thresholds.join(',') }); }}>编辑</Button><Popconfirm title="禁用规则并保留历史？" onConfirm={async () => { await api.request(`/api/alert-rules/${row.id}`, 'DELETE'); void query.load(); }}><Button danger>禁用</Button></Popconfirm></Space> }]} /><Modal title="告警规则" open={editing !== null} onCancel={() => setEditing(null)} onOk={() => void save()}><Alert type="info" title="同轮只发送最紧急一档，其余已越过档位持久去重。用户规则优先于组规则，再优先于全局规则。" /><Form form={form} layout="vertical"><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input maxLength={128} /></Form.Item><Form.Item name="kind" label="类型"><Select options={[{ value: 'traffic_limit', label: '配额百分比' }, { value: 'expiration', label: '到期前天数（0=已到期）' }]} onChange={value => form.setFieldValue('thresholds', value === 'traffic_limit' ? '80,90,100' : '7,3,1,0')} /></Form.Item><Form.Item name="thresholds" label="阈值（逗号分隔整数）" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="scopeType" label="范围"><Select options={['all', 'group', 'user'].map(value => ({ value, label: value }))} /></Form.Item><Form.Item name="scopeId" label="组或用户 ID（all 留空）"><InputNumber min={1} /></Form.Item><Form.Item name="enabled" label="启用" valuePropName="checked"><Switch /></Form.Item></Form></Modal></Card>;
}

function History({ owner = false }: { owner?: boolean }) {
  const query = useP2Data<Array<Record<string, any>>>(owner ? '/api/notifications' : '/api/my/notifications', true);
  return <Card title={owner ? '系统投递队列' : '本人通知历史'}><DataState {...query} retry={query.load} /><Table rowKey="id" dataSource={query.data || []} scroll={{ x: 600 }} columns={[{ title: '类型', dataIndex: 'kind' }, { title: '状态', dataIndex: 'state' }, { title: '收件人', render: (_, row) => row.snapshot?.recipientMasked || '—' }, { title: '错误', dataIndex: 'errorCode' }, { title: 'UTC 时间', dataIndex: 'createdAt' }, ...(owner ? [{ title: '操作', render: (_: unknown, row: Record<string, any>) => <Button disabled={row.state !== 'dead'} onClick={async () => { try { await api.request(`/api/notifications/${row.id}/retry`, 'POST'); void query.load(); } catch (error) { message.error(error instanceof Error ? error.message : '不可重试'); } }}>重试有效事件</Button> }] : [])]} /></Card>;
}

export default function Alerts() {
  const { user } = useAuth();
  const preferences = useP2Data<Preference>('/api/my/notification-preferences');
  const setPreference = async (key: 'trafficEnabled' | 'expirationEnabled', value: boolean) => { if (!preferences.data) return; try { await api.request('/api/my/notification-preferences', 'PUT', { trafficEnabled: preferences.data.trafficEnabled, expirationEnabled: preferences.data.expirationEnabled, [key]: value, expectedRevision: preferences.data.revision }); void preferences.load(); } catch (error) { message.error(error instanceof Error ? error.message : '修改失败'); } };
  const verify = async () => { try { await api.request('/api/my/email-verifications', 'POST'); message.success('若邮箱有效，验证邮件已入队，请检查收件箱'); } catch (error) { message.error(error instanceof Error ? error.message : '验证请求失败'); } };
  return <Space orientation="vertical" size="large" style={{ width: '100%' }}><Typography.Title level={2}>告警与通知</Typography.Title><Alert showIcon type="info" title="仅已验证的本人邮箱接收常规提醒" description="未验证会显示 blocked_recipient。关闭偏好后不会补发过时提醒。SMTP 为至少一次投递，不保证收件服务器去重。" action={<Button onClick={() => void verify()}>验证本人邮箱</Button>} /><DataState {...preferences} retry={preferences.load} /><Card title="本人邮件偏好"><Space wrap><label>用量提醒 <Switch checked={preferences.data?.trafficEnabled} disabled={!preferences.data} onChange={value => void setPreference('trafficEnabled', value)} /></label><label>到期提醒 <Switch checked={preferences.data?.expirationEnabled} disabled={!preferences.data} onChange={value => void setPreference('expirationEnabled', value)} /></label></Space></Card><History />{user?.role === 'owner' && <><Rules /><History owner /></>}</Space>;
}
